'use strict';

// AUTO-GENERATED by scripts/generate-modules.js - do not hand-edit.
const { SingularityModule } = require('./Singularity');

/**
 * Attaches every generated module to the client under its lowerCamel controller
 * name (e.g. client.completion, client.images, client.holonicMemory).
 */
function attachGeneratedModules(client, http) {
  client.singularity = client.singularity || new SingularityModule(http);
  return client;
}

module.exports = { attachGeneratedModules };
