// AUTO-GENERATED by scripts/generate-types.js - do not hand-edit.
import type { OASISResponse } from '../core/types';

export declare class SingularityModule {
  constructor(http: unknown);

  /** GET v1/singularity/status */
  getUnifiedStatus(args?: Record<string, any>): Promise<OASISResponse>;
}
