// AUTO-GENERATED by scripts/generate-types.js - do not hand-edit.
export interface OASISResponse<T = any> {
  isError: boolean;
  message: string | null;
  result: T;
  raw: any;
  statusCode: number;
}

export interface OASISSession {
  avatarId: string;
  username: string;
  email: string;
  firstName?: string;
  lastName?: string;
  jwtToken: string;
  refreshToken?: string;
}
