'use strict';

/**
 * Generates a .d.ts declaration file per generated module plus a top-level
 * index.d.ts, by parsing src/modules/*.js the same way generate-docs.js does.
 * Every method is typed as (args?: Record<string, any>) => Promise<OASISResponse>
 * since route shapes vary per-operation but the calling convention is uniform
 * (see docs/getting-started.md#calling-any-endpoint).
 *
 * Run with: node scripts/generate-types.js
 */

const fs = require('fs');
const path = require('path');

const modulesDir = path.join(__dirname, '..', 'src', 'modules');

function toCamel(name) {
  return name.charAt(0).toLowerCase() + name.slice(1);
}

function parseOps(src) {
  const opPattern = /this\.(\w+) = makeOperation\(http, "([^"]*)", "([A-Z]+)", "([^"]*)"\);/g;
  const ops = [];
  let m;
  while ((m = opPattern.exec(src))) {
    const [, jsName, prefix, verb, route] = m;
    ops.push({ jsName, prefix, verb, route });
  }
  return ops.sort((a, b) => a.jsName.localeCompare(b.jsName));
}

const files = fs
  .readdirSync(modulesDir)
  .filter((f) => f.endsWith('.js') && f !== 'index.js')
  .sort();

const moduleDecls = [];

for (const file of files) {
  const moduleName = file.replace(/\.js$/, '');
  const className = `${moduleName}Module`;
  const src = fs.readFileSync(path.join(modulesDir, file), 'utf8');
  const ops = parseOps(src);
  if (!ops.length) continue;

  const methodLines = ops
    .map((op) => `  /** ${op.verb} ${op.prefix}/${op.route} */\n  ${op.jsName}(args?: Record<string, any>): Promise<OASISResponse>;`)
    .join('\n\n');

  const dts = `// AUTO-GENERATED by scripts/generate-types.js - do not hand-edit.
import type { OASISResponse } from '../core/types';

export declare class ${className} {
  constructor(http: unknown);

${methodLines}
}
`;

  fs.writeFileSync(path.join(modulesDir, `${moduleName}.d.ts`), dts);
  moduleDecls.push({ moduleName, className, clientProp: toCamel(moduleName) });
}

// Shared response/core types.
fs.mkdirSync(path.join(__dirname, '..', 'src', 'core'), { recursive: true });
fs.writeFileSync(
  path.join(__dirname, '..', 'src', 'core', 'types.d.ts'),
  `// AUTO-GENERATED by scripts/generate-types.js - do not hand-edit.
export interface OASISResponse<T = any> {
  isError: boolean;
  message: string | null;
  result: T;
  raw: any;
  statusCode: number;
}

export interface OASISSession {
  avatarId: string;
  username: string;
  email: string;
  firstName?: string;
  lastName?: string;
  jwtToken: string;
  refreshToken?: string;
}
`
);

// Top-level index.d.ts wiring every module onto Web9Client.
const importLines = moduleDecls
  .map((m) => `import type { ${m.className} } from './src/modules/${m.moduleName}';`)
  .join('\n');
const propLines = moduleDecls.map((m) => `  readonly ${m.clientProp}: ${m.className};`).join('\n');

const indexDts = `// AUTO-GENERATED by scripts/generate-types.js - do not hand-edit.
import type { OASISResponse, OASISSession } from './src/core/types';
${importLines}

export type { OASISResponse, OASISSession };

export interface Web9ClientOptions {
  baseUrl?: string;
  persistSession?: boolean;
  fetchImpl?: typeof fetch;
}

export declare class HttpClient {
  constructor(options?: { baseUrl?: string; tokenStore?: unknown; fetchImpl?: typeof fetch });
  setBaseUrl(baseUrl: string): void;
  request(verb: 'GET' | 'POST' | 'PUT' | 'DELETE', path: string, options?: Record<string, any>): Promise<OASISResponse>;
  get(path: string, options?: Record<string, any>): Promise<OASISResponse>;
  post(path: string, options?: Record<string, any>): Promise<OASISResponse>;
  put(path: string, options?: Record<string, any>): Promise<OASISResponse>;
  delete(path: string, options?: Record<string, any>): Promise<OASISResponse>;
}

export declare class TokenStore {
  constructor(options?: { persist?: boolean });
  getSession(): OASISSession | null;
  getToken(): string | null;
  setSession(session: OASISSession | null): void;
  clear(): void;
}

export declare const DEFAULT_BASE_URL: string;

export declare class Web9Client {
  constructor(options?: Web9ClientOptions);
  readonly http: HttpClient;
  readonly tokenStore: TokenStore;
${propLines}
  setBaseUrl(baseUrl: string): void;
  setToken(jwtToken: string, sessionExtras?: Partial<OASISSession>): void;
}

export default Web9Client;
`;

fs.writeFileSync(path.join(__dirname, '..', 'index.d.ts'), indexDts);

console.log(`Generated .d.ts for ${moduleDecls.length} modules + index.d.ts + core/types.d.ts`);
