'use strict';

/**
 * One-time/repeatable codegen: reads endpoints.json (extracted from the WEB9 AI
 * Layer WebAPI controller source) and emits one module file per controller under
 * src/modules/. Every generated method is a real HTTP call via routeHelper -
 * there is no mocked data anywhere in the output.
 *
 * Run with: node scripts/generate-modules.js
 */

const fs = require('fs');
const path = require('path');

const endpoints = JSON.parse(fs.readFileSync(path.join(__dirname, '..', 'endpoints.json'), 'utf8'));
const outDir = path.join(__dirname, '..', 'src', 'modules');

function toCamel(name) {
  return name.charAt(0).toLowerCase() + name.slice(1);
}

function controllerToModuleName(filename) {
  return filename.replace(/Controller\.cs$/, '');
}

const manifest = [];

for (const [filename, info] of Object.entries(endpoints)) {
  const moduleName = controllerToModuleName(filename);
  const className = `${moduleName}Module`;
  const routePrefix = info.route_prefix;
  const opNames = Object.keys(info.ops).sort();

  if (!opNames.length) continue;

  const methods = opNames.map((opName) => {
    const op = info.ops[opName];
    const jsName = toCamel(opName);
    const routeLiteral = JSON.stringify(op.route || '');
    const opts = {};
    if (op.query && op.query.length) opts.query = op.query;
    if (op.bodyParam) opts.bodyParam = op.bodyParam;
    const optsLiteral = Object.keys(opts).length ? `, ${JSON.stringify(opts)}` : '';
    const queryNote = op.query && op.query.length ? ` (query: ${op.query.join(', ')})` : '';
    const bodyNote = op.bodyParam ? ` (body: ${op.bodyParam})` : '';
    return `    // ${op.verb} ${routePrefix}/${op.route}${queryNote}${bodyNote}\n    this.${jsName} = makeOperation(http, ${JSON.stringify(
      routePrefix
    )}, ${JSON.stringify(op.verb.toUpperCase())}, ${routeLiteral}${optsLiteral});`;
  });

  const source = `'use strict';

// AUTO-GENERATED by scripts/generate-modules.js from endpoints.json - do not hand-edit.
// Regenerate with: node scripts/generate-modules.js

const { makeOperation } = require('../core/routeHelper');

/**
 * Generated wrapper for ${routePrefix} (source: WEB9 Singularity WebAPI ${filename}).
 * Every method takes a single args object: path-template tokens (e.g. {id})
 * are consumed from it automatically; any remaining keys are sent as the
 * query string (GET/DELETE) or JSON body (POST/PUT).
 */
class ${className} {
  constructor(http) {
    this._http = http;

${methods.join('\n')}
  }
}

module.exports = { ${className} };
`;

  fs.writeFileSync(path.join(outDir, `${moduleName}.js`), source);
  manifest.push({ moduleName, className });
}

// Emit an index that wires every generated module onto the client.
const importLines = manifest.map((m) => `const { ${m.className} } = require('./${m.moduleName}');`).join('\n');
const propLines = manifest
  .map((m) => `  client.${toCamel(m.moduleName)} = client.${toCamel(m.moduleName)} || new ${m.className}(http);`)
  .join('\n');

const indexSource = `'use strict';

// AUTO-GENERATED by scripts/generate-modules.js - do not hand-edit.
${importLines}

/**
 * Attaches every generated module to the client under its lowerCamel controller
 * name (e.g. client.completion, client.images, client.holonicMemory).
 */
function attachGeneratedModules(client, http) {
${propLines}
  return client;
}

module.exports = { attachGeneratedModules };
`;

fs.writeFileSync(path.join(outDir, 'index.js'), indexSource);

console.log(`Generated ${manifest.length} modules covering ${Object.values(endpoints).reduce((n, i) => n + Object.keys(i.ops).length, 0)} operations.`);
